### ISSUE TITLE
Falsche UUID

### ISSUE THREAD

**Issue by mawe1202** [awaescher/homebridge-kiwigrid#1]
Hallo Andreas,

danke für das Plugin, es wäre toll den Akkustand von unterwegs abzufragen. Leider krieg ich es n nicht zum laufen. Beim Hochfahren der HB kommt folgender Fehle ( HB läuft aber durch ):

ERROR received from http://192.000.000.000/rest/kiwigrid/wizard/devices: Error: UUID 'urn:solarwatt:myreserve:bc:a30b000b0f4d' is not a valid UUID. Try using the provided 'generateUUID' function to create a valid UUID from any arbitrary string, like a serial number.

Bei Eingabe der IP in den Browser kommt dir korrekte Antwort:

[{"id":"000000-00000e-0000-0000-a129684aed7f","name":"Goethe-Str","deviceClass":"com.kiwigrid.devices.location.Location","powerConsumed":527,"powerProduced":730,"powerIn":0,"powerOut":203}, {"id":"0000000-0000-0000-0000-0fa629c500a4","name":"PV-Solarwatt","deviceClass":"com.kiwigrid.devices.pvplant.PVPlant","powerACOut":730}]
 
ID und IP verfälscht..

Kannst du mir helfen das zum Laufen zu bekommen ?

Danke für Deine Mühe.

LG Mario

**Comment by awaescher** [comment]
Hi Mario,

ja, ich verstehe das Problem. Homebridge möchte eine global eindeutigte ID haben, also z.B. `3a4307cf-0b48-4208-baef-53e82ae5a677`. Meine Batterie liefert eine entsprechende ID zurück, die ich 1:1 an Homebridge weiterleite. In deinem Fall kommt aber eine Zeichenfolge zurück, die dem UUID-Pattern nicht entspricht: `urn:solarwatt:myreserve:bc:a30b000b0f4d`. 
In diesem Fall muss ich wohl einen Fallback einbauen, der über die in der Fehlermeldung genannte Methode `generateUUID()` eine eindeutige ID generiert und weiterverwendet.

Werde ich mir anschauen, aber ich weiß noch nicht, wann ich dazu komme.

**Comment by mawe1202** [comment]
Danke für Deine schnelle Antwort, schön das Dich der Sache annimmst. Es ist echt ein "Nice to have" aber es kommt jetzt
nicht auf den Tag an. Gut zu wissen das es wohl demnächst funktioniert... :-)

In diesem Sinne - einen schönen Feierabend

**Comment by awaescher** [comment]
Ich hatte vorhin unerwarteterweise etwas Zeit gefunden 😊
Das ganze Plugin ist ein Nice-To-Have, so gehts mir ja auch. Aber ich finde es einfach gut, die Info in HomeKit zu haben. Zumal wir schon ab und an Ausfälle hatten und dann lange nicht bemerkten, dass der Strom nicht gespeichert wurde.

Schau' mal in deiner Homebridge nach, dort sollte Version 1.2.2 verfügbar sein.
Ich hab es jetzt so [geändert](https://github.com/awaescher/homebridge-kiwigrid/commit/7857cbc9f801cf1eb51be29badc0c7a90f45450b), dass die GUID des Herstellers verwendet wird, wenn sie im UUID-Format vorliegt (wie bisher) - wenn nicht, erzeuge ich aus der Hersteller-GUID eine UUID.

**Comment by mawe1202** [comment]
Na super... Ich hab es installiert und das Icon von MyReserv wird jetzt angezeigt und im Log ist keine Fehlermeldung mehr ..... aaaber es aktualisiert nicht, es läuft jetzt etwa 10 min und ist bei 0%. Die App zeigt 98%.

Ja genau wegen der Kontrolle finde ich es auch so toll. Die Erzeugung selbst lass ich mir auch schon in  HB als Screenshot anzeigen, nur der Akku war da nicht bei.

**Comment by awaescher** [comment]
Oh nein. Dann sieht die JSON-Antwort deines Gateways bestimmt anders aus als bei mir. 
Würde es dir was ausmachen, mit die JSON-Antwort zu senden, die bei dieser URL zurückkommt?

`http://IPADDRESS/rest/kiwigrid/wizard/devices`

Diese wird ziemlich umfangreich sein und auch Daten enthalten, mit denen sich Rückschlüsse auf deinen Wohnort ziehen lassen. Also bitte gern verfremden und nicht öffentlich posten.

Wenn das für die okay wäre, dann einfach per Email (in den Commits ersichtlich) oder per [Twitter DM](https://twitter.com/waescher).

**Comment by mawe1202** [comment]
Danke nochmal das Dich damit befasst.

So, hier das File

**Comment by mawe1202** [comment]
Ja klar ist das ok, nur ich find nicht die mail-adr. Sry, was sind die Commits?

**Comment by awaescher** [comment]
Okay 😄
Das sind die „Pakete“ mit denen Code in GitHub eingecheckt werden. Dort ist die Email öffentlich einsehbar.
Aber was soll’s: bitte einfach an awaescher@sodacore.net

**Comment by mawe1202** [comment]
Nachdem die Homebridge nun das 2. Mal neu gestartet wurde zeigt das MyReserve Icon den aktuellen Ladestand an. 

Danke an den Entwickler für die Hilfe und den tollen Support
